spring:
  application:
    name: gateway-playground

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/user-service/**
        - id: car-info-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/car-info-service/**
        - id: car-listing-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/car-listing-service/**

springdoc:
  webjars:
    prefix: /api
  cache:
    disabled: true
